[package]
name = "generator"
version = "0.3.0"
edition = "2021"

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
tonic = { version = "0.13.1", features = ["tls-ring", "gzip"] }
tonic-build = { version = "0.13.1", features = [] }
