[package]
name = "t-invest-sdk"
version = "0.6.1"
edition = "2021"
authors = ["Artem Evsevev <artem@qrsoft.ru>"]
description = "T-Bank Invest API SDK. Клиент для работы с T-Invest API от Т-Банка (Тинькофф)."
license = "MIT"
readme = "README.md"
repository = "https://github.com/artemevsevev/t-invest-sdk"
keywords = ["trading", "tbank", "tinvest", "finance", "sdk"]
categories = ["finance"]
exclude = ["investAPI/*"]

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
rust_decimal = "1.37.1"
thiserror = "2.0.12"
tonic = { version = "0.13.0", features = [
    "tls-ring",
    "tls-native-roots",
    "gzip",
] }
uuid = { version = "1.16.0", features = ["v4"] }

[dev-dependencies]
rust_decimal_macros = "1.37.1"
