[package]
name = "t-invest-sdk"
version = "0.2.2"
edition = "2021"
authors = ["Artem Evsevev <artem@qrsoft.ru>"]
description = "T-Invest API SDK"
license = "MIT"
readme = "README.md"
repository = "https://github.com/artemevsevev/t-invest-sdk"
keywords = ["api", "trading"]
categories = ["finance"]
exclude = ["investAPI/*"]

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
thiserror = "2.0.11"
tonic = { version = "0.12.3", features = ["tls", "tls-native-roots", "gzip"] }
uuid = { version = "1.13.1", features = ["v4"] }
